var letter = require('./letter.js');

// holds your words that you want to use 

var Wordlist = 
    ['THE HOBBIT AN UNEXPECTED JOURNEY', 
'THE HOBBIT THE DESOLATION OF SMAUG', 
'THE HOBBIT THE BATTLE OF THE FIVE ARMIES',
'THE LORD OF THE RINGS THE FELLOWSHIP OF THE RING',
'THE LORD OF THE RINGS THE TWO TOWERS',
'THE LORD OF THE RINGS THE RETURN OF THE KING',
'STAR WARS A NEW HOPE',
'STAR WARS EMPIRE STRIKES BACK',
'STAR WARS RETURN OF THE JEDI',
'STAR WARS THE PHANTOM MENACE',
'STAR WARS ATTACK OF THE CLONES',
'STAR WARS REVENGE OF THE SITH',
'STAR WARS THE FORCE AWAKINS',
'STAR WARS THE LAST JEDI',
'ROUGE One A STAR WARS STORY',
'SOLO A STAR WARS STORY']

module.exports = Wordlist ;
