module.exports =
    ['the hobbit an unexpected journey',
        'the hobbit the desolation of smaug',
        'the hobbit the battle of the five armies',
        'the lord of the rings the fellowship of the RING',
        'the lord of the rings the two towers',
        'the lord of the rings the return of the king',
        'star wars a new hope',
        'star wars empire strikes back',
        'star wars return of the jedi',
        'star wars the phantom menace',
        'star wars attack of the clones',
        'star wars revenge of the sith',
        'star wars the force awakens',
        'star wars the last jedi',
        'rogue one a star wars story',
        'solo a star wars story']